/**
 * German UI strings only. English copy lives in the HTML; script snapshots it on load.
 * When you add new text: put English in HTML, add data-i18n="your.key", then add the key here.
 */
window.FHV_I18N_DE = {
    'nav.dashboard': 'Startseite',
    'nav.courses': 'Kurse',
    'nav.resources': 'Ressourcen',
    'nav.benefits': 'Vorteile',
    'profile.languageLabel': 'Sprache',
    'profile.languageToggleAriaDe': 'Sprache: Deutsch. Klick für Englisch.',
    'profile.notifications': 'Benachrichtigungen',
    'profile.settings': 'Profileinstellungen',
    'profile.logout': 'Abmelden',

    'index.documentTitle': 'Startseite – FHV Student Hub',
    'index.cafeteriaTitle': 'Mensa-Speiseplan',
    'index.cafeteriaBody': 'Wochenmenüs für die FH-Mensa (Ländle Gastronomie).',
    'index.internalLinksHeading': 'Interne Studierenden-Links',
    'index.link.a5.desc': 'Stundenplan, Noten, Prüfungstermine',
    'index.link.ilias.desc': 'Kursmaterial, Aufgaben, Abgaben',
    'index.link.myfhv.desc': 'Druckguthaben, Evaluierungen, Support',
    'index.link.webmail.desc': 'Outlook für FHV-Mails',
    'index.link.oeh.desc': 'Studierendenvertretung, Events, Mitbestimmung',
    'index.link.inside.desc': 'Studieninfos und interne News',
    'index.link.olav.desc': 'Bibliothekssuche und Literatur',
    'index.eventsHeading': 'Bevorstehende Veranstaltungen',
    'index.eventsSub': 'Events filtern und mit dem Schalter neben dem Filter zwischen Agenda- und Kalenderansicht wechseln.',
    'index.viewTooltipList': 'Agenda-Ansicht',
    'index.viewTooltipCalendar': 'Kalenderansicht',
    'index.cal.mo': 'Mo',
    'index.cal.tu': 'Di',
    'index.cal.we': 'Mi',
    'index.cal.th': 'Do',
    'index.cal.fr': 'Fr',
    'index.cal.sa': 'Sa',
    'index.cal.su': 'So',
    'index.calendarLegendFhv': 'FHV-Event',
    'index.calendarLegendOh': 'ÖH-Event',
    'index.filterLabel': 'Filter',
    'index.filter.all': 'Alle Events',
    'index.filter.fhv': 'Nur FHV',
    'index.filter.oh': 'Nur ÖH',
    'index.event1.title': 'Datenbank-Workshop',
    'index.event1.meta': '14:00–16:00, Raum U206',
    'index.event2.title': 'Semester Opening Party',
    'index.event2.meta': '20:00, Fischbach',
    'index.event3.title': 'Karrieremesse',
    'index.event3.meta': '16:00–19:00, Foyer',
    'index.event4.title': 'Filmabend',
    'index.event4.meta': '18:00, ÖH-Raum',
    'index.event5.title': 'Cafè Campus Spieleabend',
    'index.event5.meta': 'Abends, Campus',
    'index.event6.title': 'WiDS – Wissenschaftliche Vorträge',
    'index.event6.meta': '9:00–18:00, Foyer',
    'index.event7.title': 'Töpferkurs',
    'index.event7.meta': 'Details auf der ÖH-Webseite',
    'index.event8.title': 'Paint & Wine',
    'index.event8.meta': 'Anmeldung über die ÖH',
    'index.event9.title': 'Sommersemester-Abschlussfeier',
    'index.event9.meta': 'Feier zum Semesterende',
    'courses.documentTitle': 'Kurse – FHV Student Hub',
    'courses.breadcrumb': '<a href="index.html" class="hover:text-fhv-blue transition">Startseite</a> / Kurse',
    'courses.pageTitle': 'Deine Kurse – SS 2026',
    'courses.intro': 'Wechsle zwischen aktuellem und vergangenen Semestern. Für jeden Kurs denselben ILIAS-Kurzlink.',
    'courses.semesterFilterLabel': 'Semester',
    'courses.optCurrent': 'Aktuelles Semester (SS 2026)',
    'courses.optS1': 'Semester 1',
    'courses.optS2': 'Semester 2',
    'courses.optS3': 'Semester 3',
    'courses.optS4': 'Semester 4',
    'courses.optS5': 'Semester 5',
    'courses.pastMeta': 'Vergangenes Semester',
    'courses.card1.title': 'Künstliche Intelligenz',
    'courses.card1.meta': 'Nächster Termin: Mo 13:10, Raum U427',
    'courses.card2.title': 'Seminar: Bachelorarbeit',
    'courses.card2.meta': 'Nächster Termin: Di 18:00, Online',
    'courses.card3.title': 'Fortgeschrittenes Datenmanagement',
    'courses.card3.meta': 'Nächster Termin: Mi 13:10, Raum U430',
    'courses.card4.title': 'Low-Code-Entwicklung',
    'courses.card4.meta': 'Nächster Termin: Do 14:00, Raum U226',
    'courses.card5.title': 'Wahlfach: Hackathon',
    'courses.card5.meta': 'Term Paper fällig bis 24. Mai',
    'courses.card6.title': 'Bachelorarbeit &amp; Prüfung',
    'courses.card6.meta': 'Informationen folgen',
    'courses.s1.c1.title': 'Web-Front-End-Technologien',
    'courses.s1.c2.title': 'Relationale Datenbanken',
    'courses.s1.c3.title': 'Informationssysteme',
    'courses.s1.c4.title': 'Business Process Management',
    'courses.s1.c5.title': 'Wissenschaftliche Grundlagen und Methoden anhand Fallstudien zur digitalen Innovation',
    'courses.s1.c6.title': 'Wirtschaftliche Grundlagen',
    'courses.s2.c1.title': 'Programmierparadigmen und -techniken',
    'courses.s2.c2.title': 'Verteilte und nicht-relationale Datenbanken',
    'courses.s2.c3.title': 'IT-Produkt- und Servicemanagement',
    'courses.s2.c4.title': 'Human-Centered Design',
    'courses.s2.c5.title': 'Finanzmanagement',
    'courses.s2.c6.title': 'Technologie- und Projektmanagement',
    'courses.s2.c7.title': 'Strategie und Marketing',
    'courses.s3.c1.title': 'Angewandte Mathematik',
    'courses.s3.c2.title': 'Skript- und Webtechnologien',
    'courses.s3.c3.title': 'Systemanalyse',
    'courses.s3.c4.title': 'Modellierung cyber-physischer Systeme',
    'courses.s3.c5.title': 'Innovationsmethoden',
    'courses.s3.c6.title': 'Innovationsprojekt – Konzeption und Product-Market-Fit',
    'courses.s3.c7.title': 'Personal und Organisation',
    'courses.s3.c8.title': 'Unternehmensethik und Corporate Social Responsibility',
    'courses.s4.c1.title': 'Lineare Algebra und Operations Research',
    'courses.s4.c2.title': 'Applikationsintegration und Sicherheit',
    'courses.s4.c3.title': 'Integrierte Informationssysteme',
    'courses.s4.c4.title': 'Innovationsprojekt – Softwareentwurf und -implementierung',
    'courses.s4.c5.title': 'IT-Recht',
    'courses.s4.c6.title': 'Logistik und Supply-Chain-Management',
    'courses.s5.c1.title': 'Angewandte Statistik und Datenanalyse',
    'courses.s5.c2.title': 'Softwareprozesse und Qualität',
    'courses.s5.c3.title': 'Wissensbasierte Systeme',
    'courses.s5.c4.title': 'IT-Management',
    'courses.s5.c5.title': 'Innovationsprojekt – Marketing und kontinuierlicher Verbesserungsprozess',
    'courses.s5.c6.title': 'Corporate Entrepreneurship und Start-up-Kultur',

    'resources.documentTitle': 'Ressourcen – FHV Student Hub',
    'resources.breadcrumb': '<a href="index.html" class="hover:text-fhv-blue transition">Startseite</a> / Ressourcen',
    'resources.pageTitle': 'Lernressourcen',
    'resources.intro': 'Zentrale Einstiege für Unterlagen, Peer-Learning und Chancen im europaweiten Hochschulnetzwerk.',
    'resources.card1.title': 'Vorlesungsunterlagen',
    'resources.card1.body': 'Skripte des aktuellen und vergangener Semester, Altklausuren und geteilte Dateien für dein Studium.',
    'resources.card1.cta': 'Unterlagen öffnen',
    'resources.card2.title': 'Lerngruppen',
    'resources.card2.body': 'Finde oder organisiere Lerntreffen und Prüfungsvorbereitungsgruppen in deinem Studiengang.',
    'resources.card2.cta': 'Lerngruppen durchsuchen',
    'resources.card3.body': 'Europäisches Hochschulnetzwerk: Mobilität, Forschung, gemeinsame Module und Partnerhochschulen für Lernmöglichkeiten.',
    'resources.card3.cta': 'RUN-EU-Portal',

    'benefits.documentTitle': 'Vorteile & ÖH – FHV Student Hub',
    'benefits.breadcrumb': '<a href="index.html" class="hover:text-fhv-blue transition">Startseite</a> / Vorteile &amp; ÖH',
    'benefits.heroTitle': 'Österreichische Hochschüler:innenschaft (ÖH)',
    'benefits.oehIntro': 'Kurz zur ÖH an der FHV.',
    'benefits.oehTile1Title': 'Aufgaben',
    'benefits.oehTile1Detail': 'Die ÖH vertritt Studierende: akademische Interessen, soziale Themen und Studienqualität an Unis und Fachhochschulen in Österreich.',
    'benefits.oehTile2Title': 'Vor Ort',
    'benefits.oehTile2Detail': 'Lokale ÖH: Veranstaltungen, Kampagnen und verhandelte Vorteile fürs ganze Semester.',
    'benefits.oehTile3Title': 'Mitgliedschaft',
    'benefits.oehTile3Detail': 'ECTS-Anrechnung, bis zu 30 % weniger Anwesenheitspflicht, Netzwerk an der FHV und mehr!',
    'benefits.oehJoinCta': 'Mach mit bei der ÖH!',
    'benefits.heroCta1': 'ÖH FHV Webseite',
    'benefits.heroCta2': 'Veranstaltungskalender',
    'benefits.sideTitle': 'Semester-Vorteile',
    'benefits.sideIntro': 'Für alle FHV- und Incoming-Studierenden.',
    'benefits.tileHoverHint': 'Fahr mit der Maus über eine Kachel für Details.',
    'benefits.tile1Title': 'ÖH-Helpline',
    'benefits.tile1Detail': 'Kostenlose, vertrauliche und unkomplizierte psychotherapeutische Unterstützung durch eine therapeutische Fachkraft.',
    'benefits.tile2Title': 'Freizeit',
    'benefits.tile2Detail': '50 % Rabatt auf Fremdsprachenkurse beim WIFI Vorarlberg &amp; 50 % auf lokale Kinotickets.',
    'benefits.tile3Title': 'Sport',
    'benefits.tile3Detail': '20 % Boulderrabatt, 50 % Aikido-Rabatt, kostenlose Yoga-Kurse an der FHV, Padelzone-Rabatte u. a.',
    'benefits.tile4Title': 'Dornbirner Hallenbad &amp; Waldbad',
    'benefits.tile4Detail': 'Freier Eintritt mit FHV-Studierendenausweis.',
    'benefits.tile5Title': 'Karrenseilbahn',
    'benefits.tile5Detail': 'Kostenloser Zugang bis August mit FHV-Studierendenausweis.',
    'benefits.tile6Title': 'Plagiatsscan',
    'benefits.tile6Detail': 'Pro Semester zweimal kostenlos deine Arbeit auf Plagiate prüfen lassen.',
    'benefits.tile7Title': 'ÖH-Früchte',
    'benefits.tile7Detail': 'Zweimal pro Woche Kisten regionales Obst vor dem ÖH-Raum (U315) für Studierende.',
    'benefits.tile8Title': 'Bewerbungsfotos',
    'benefits.tile8Detail': 'Einmal pro Semester kostenlose professionelle Fotos für Bewerbungsunterlagen.',
    'benefits.tile9Title': 'Studiengangs-Semesterevent',
    'benefits.tile9Detail': 'Netzwerktreffen im Jahrgang mit bis zu 15 € pro Person Förderung.',
    'benefits.viewAll': 'Alle anzeigen →',
    'benefits.footerNote': 'Alle Semester-Vorteile und ÖH-Angebote findest du auf der ÖH FHV Webseite.',
};
